name: Build and Push Docker Image to Docker Hub
on: push
jobs:
  push_to_registry:
    name: push docker image to hub
    runs-on: ubuntu-latest
    steps:
      - name: check repository
        uses: actions/checkout@v4
      - name: login to docker registry
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}
      - name: Populate Dockerfile
        env:
          DOCKERFILE_CONTENT: ${{secrets.DOCKERFILE}}
        run: |
          touch Dockerfile
          echo "${DOCKERFILE_CONTENT}" >> Dockerfile
      - name: Create .env file
        env:
          ENV_CONTENT: ${{secrets.ENVFILE}}
        run: |
          touch .env 
          echo "${ENV_CONTENT}" >> ./.env
          echo "ls -la ./"

    - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      # - name: build and push docker image to registry
      #   uses: docker/build-push-action@v5
      #   with:
      #     context: Dockerfile
      #     push: true
      #     tags: ${{secrets.DOCKERHUB_USERNAME}}/chess-pgn-exporter:latest